name: ARM Cross Builds

on:
  push:
    branches: [ master, arm-cross-builds ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Toolchain
      run: |
        curl -L -O https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
        tar -xf gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
    - name: Configure aarch64-none-linux-gnu
      run: |
        cd dist/gcc-compatible
        export TOOLCHAIN=$PWD/../../gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu
        ./configure -target aarch64-none-linux-gnu
    - name: Make
      run: |
        cd dist/gcc-compatible
        make -j
