name: ARM Cross Builds

on:
  push:
    branches: [ master, arm-cross-builds ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dist/gcc-compatible

    steps:
    - uses: actions/checkout@v2
    - name: Setup Toolchain
      working-directory: $HOME
      run: |
        wget https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz?revision=61c3be5d-5175-4db6-9030-b565aae9f766&la=en&hash=0A37024B42028A9616F56A51C2D20755C5EBBCD7
        tar -xfv gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
    - name: Configure aarch64-none-linux-gnu
      run: |
        export TOOLCHAIN=$HOME/gcc-aarch64-none-linux/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu
        ./configure -target aarch64-none-linux-gnu
    - name: Make
      run: make -j
