name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Info
      run: pwd && ls -l
    - name: Build the Docker image
      run: ./build_local.sh .docker/build/github-actions-config.json
