name: HACL* CI build in Docker

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build HACL* CI in docker
      run: ./build_local.sh hacl-star
