name: Build MOZ

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: cp .docker/build/mozilla/build_local.sh . 
    - name: Build
      run: ./build_local.sh .docker/build/mozilla/config.json
